### ISSUE TITLE
Gaussian Noise

### ISSUE THREAD

**Issue by funnypig521** [Vegetebird/MHFormer#59]
Excuse me, I noticed you add different gaussian noise for 2D input in your Supplementary Material. I try to add noise for input but can not reproduce your result, could you please tell me how to add gaussian noise correctly. Thanks a lot!!!!!!!!!!!!!

**Comment by Vegetebird** [comment]
We use 'np.random.normal' to add gaussian noise.

**Comment by funnypig521** [comment]
Yeah,  I know it. What I mean is where do i add the code？ Can I add it in main.py of line 39?

**Comment by Vegetebird** [comment]
Yes, it is right. 

##----------Gaussian----------##
gaussian_scale = 20 / 500

input_2D = input_2D.cpu().numpy()
nosie = np.random.normal(0, gaussian_scale, input_2D.shape)
input_2D = input_2D + nosie
input_2D = torch.from_numpy(input_2D.astype('float32'))
input_2D = input_2D.cuda()
##----------------------------##

But need to ‘/500’ due to the input_2D is normalized in https://github.com/Vegetebird/MHFormer/blob/fcf238631016f906477ec9c1d17582097ecf9803/common/camera.py#L7
